pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
    GITHUB_URL = "https://github.com/cmdhellothere/codeby-devops.git"
}

    stages {
        stage('checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: env.GITHUB_URL
            }
        }
        stage('Build') {
            steps {
                dir('lesson26/app') {
                    sh 'mvn -B -DskipTests clean package'
                    }
                
            }
        }
        stage('Test') {
            steps {
                dir('lesson26/app') {
                sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'lesson26/app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod +x lesson26/app/jenkins/scripts/deliver.sh'
                sh './lesson26/app/jenkins/scripts/deliver.sh'
            }
        }
    }
}