services:
  db:
    image: mysql:8.2.0
    container_name: db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - musqul.env
      
  app:
    image: wordpress:6.4.2-php8.1-apache
    container_name: app
    depends_on:
      - db
    volumes:
      - wp-data:/var/www/html
    networks:
      - frontend
      - backend
    env_file:
      - wp.env
    
      
  proxy:
    image: nginx:1.24-bullseye
    container_name: proxy
    depends_on:
      - app
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    ports:
      - 80:82
    


volumes:
  db-data:
  wp-data:

networks:
  frontend:
  backend:
