Vagrant.configure("2") do |config|
config.vm.define "server" do |server|

    server.vm.box = "sloopstash/ubuntu-22-04"
    server.vm.network "private_network", ip: "192.168.201.21"
    server.vm.hostname = "server"
    server.vm.provider "vmware_fusion" do |vb| 
       vb.vmx["memsize"] = "4048"
       vb.vmx["numvcpus"] = "2"
      end
    server.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.201.20 client" | sudo tee -a /etc/hosts
      sudo ssh-keygen -C vagrant@localhost -f "/home/vagrant/.ssh/id_rsa" -q -N "" 
      sudo cat "/home/vagrant/.ssh/id_rsa.pub" >> "/root/.ssh/authorized_keys"
      sudo cat "/home/vagrant/.ssh/id_rsa.pub" >> "/home/vagrant/.ssh/authorized_keys"
      sudo chmod 644 "/home/vagrant/.ssh/authorized_keys"
      sudo chown -R vagrant:vagrant "/home/vagrant/.ssh"  
    SHELL

  end

 config.vm.define "client" do |client|

    client.vm.box = "sloopstash/ubuntu-22-04"
    client.vm.network "private_network", ip: "192.168.201.20"
    client.vm.hostname = "client"
    client.ssh.password = "vagrant" 
    client.vm.provider "vmware_fusion" do |vb| 
       vb.vmx["memsize"] = "4048"
       vb.vmx["numvcpus"] = "2"
      end
    client.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.201.21 server" | sudo tee -a /etc/hosts
      sudo ssh-keygen -C vagrant@localhost -f "/home/vagrant/.ssh/id_rsa" -q -N "" 
      sudo cat "/home/vagrant/.ssh/id_rsa.pub" >> "/root/.ssh/authorized_keys"
      sudo cat "/home/vagrant/.ssh/id_rsa.pub" >> "/home/vagrant/.ssh/authorized_keys"
      sudo chmod 644 "/home/vagrant/.ssh/authorized_keys"
      sudo chown -R vagrant:vagrant "/home/vagrant/.ssh" 
      sudo apt-get install sshpass -y
      sudo sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/id_rsa.pub -o StrictHostKeyChecking=no vagrant@server

    SHELL

    client.trigger.after :up do |trigger| 
       trigger.warn = "conn to client"
       trigger.run = {inline: "vagrant ssh client -c 'ssh -i /home/vagrant/.ssh/id_rsa -o StrictHostKeyChecking=no server'"} 
       end
    end
end


 


